close all;
clear all;
clc;

%% Criando a Antenas
%Antena sem deflexão traseira
antena1 = phased.IsotropicAntennaElement(...
    'FrequencyRange', [3e8 1e9],... %Faixa de Frequência
    'BackBaffled', false) %Deflexão Traseira

%Antena com deflexão traseira
antena2 = phased.IsotropicAntennaElement(...
    'FrequencyRange', [3e8 1e9],... %Faixa de Frequência
    'BackBaffled', true) %deflexão traseira
%% Plotando a resposta das antenas à uma frequência
figure(1)
plotResponse(...
    antena1,1e9,...
    'Format', 'Polar',... %Formato do gráfico
    'RespCut', '3D',... %Corte da resposta
    'Unit','pow'); %unidade do gráfico

figure(2)
plotResponse(...
    antena2, 1e9,...
    'Format', 'Polar',...
    'RespCut', '3D',...
    'Unit', 'pow');

figure(3)
plotResponse(...
    antena2, 1e9,...
    'Format', 'Polar',...
    'RespCut', 'Az',... %Corte da Resposta
    'Unit','db');

figure(4)
plotResponse(...
    antena2, 1e9,...
    'Format', 'Polar',...
    'RespCut', 'El',...
    'Unit','db');
    